coverage:
    status:
        project:
            default:
                # The build fails if total project coverage drops by more than 3%
                target: auto
                threshold: "3%"
        changes: false
        patch: false
