exclude: '^$'
fail_fast: false
repos:
- repo: local
  hooks:
  - id: asserts-docker
    name: Running Asserts on the code
    description: Run Asserts to perform SAST
    entry: -v CODE_PATH/src:/code fluidattacks/asserts:latest /code/asserts.sh
    files: '\.(py|js)'
    pass_filenames: false
    language: docker_image
    minimum_pre_commit_version: 0.18.0
    verbose: true