################################################################
#Archivo de configuracion del servicio de integración continua.#
################################################################
---
version: 2
jobs:
  build:
    working_directory: /tmp/fluid-integrates
    machine: true
    evironment:
      - USER: root
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: >
           gem install overcommit
      - run:
          name: Vault file
          command: >
              sudo echo $VAULT > ~/.vault.txt &&
              sudo echo $VAULT > /tmp/.vault.txt

      - run:
          name: pip installations
          command: >
                sudo apt-get install -y python-dev python-pip &&
                pip install --upgrade -r requirements.txt

      - run:
          name: Ansible lints
          command: >
                ansible-lint deploy/main.yml

      - run:
          name: Run prospector
          command: >
                prospector -u django app &&
                prospector -u django fluidintegrates

      - run:
          name: Docker Login
          command: >
                sudo docker -D login -u $DOCKER_USER -p $DOCKER_PASSWD -e $DOCKER_EMAIL

      - run:
          name: Build container
          command: sudo deploy/build.sh $CIRCLE_BRANCH

      - run:
          name: Run asserts
          command: python deploy/asserts-checks.py

      # Deploy master
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then sudo docker -D login -u $DOCKER_USER -p $DOCKER_PASSWD -e $DOCKER_EMAIL && \
              sudo docker -D push technologyatfluid/integrates:$CIRCLE_BRANCH;
            fi
