################################################################
#Archivo de configuracion del servicio de integración continua.#
################################################################
---
version: 2
jobs:
  build:
    working_directory: /tmp/fluid-integrates
    machine: true
    evironment:
      - USER: root
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: >
           sudo apt-get install -y software-properties-common &&
           gem install overcommit
      - run:
          name: Vault file
          command: >
              sudo echo $VAULT > ~/.vault.txt &&
              sudo echo $VAULT > /tmp/.vault.txt
      - run:
          name: add ansible repo
          command: >
                sudo echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu
                trusty main" | sudo tee -a /etc/apt/sources.list &&  sudo
                apt-get update
      - run:
          name: pip installations
          command: >
                sudo apt-get install -y python-dev python-pip && sudo
                pip install --upgrade --force pip setuptools && sudo pip
                install ansible-lint && sudo pip install pep257 pep8
                pyflakes pylint flake8 yamllint
      - run:
          name: Install ansible
          command: sudo apt-get install -y --force-yes ansible
      - run:
          name: Ansible lints
          command: >
                ansible-lint ansible-lint deploy/main.yml
#      - run:
#          name: Overcommit
#          command: overcommit --sign && overcommit --run

      - run:
          name: Bundle install
          command: bundle install

      - run:
          name: Make integrates tests
          command: >
                cp /tmp/.vault.txt deploy/ &&
                cd deploy && bundle exec rspec

      - run:
          name: Install FLUIDAsserts
          command: >
                sudo apt-get install -y libffi-dev libssl-dev g++ gcc &&
                pip install fluidasserts

      - run:
	  name: Build container
          command: sudo deploy/build.sh

      - run:
          name: Run asserts
          command: python deploy/asserts-checks.py

      # Deploy master
      - deploy:
          command: >
                sudo docker -D login -u $DOCKER_USER -p $DOCKER_PASSWD -e $DOCKER_EMAIL && 
                sudo docker -D push technologyatfluid/integrates:$CIRCLE_BRANCH
