################################################################
#Archivo de configuracion del servicio de integración continua.#
################################################################
---
version: 2
jobs:
  build:
    working_directory: /tmp/fluid-integrates
    machine: true
    evironment:
      - USER: root
    steps:
      - checkout
      - run:
          name: Update
          command: sudo apt-get update
      - run:
          name: Install dependencies
          command: >
           gem install overcommit
      - run:
          name: Vault file
          command: >
              sudo echo $VAULT > ~/.vault.txt &&
              sudo echo $VAULT > /tmp/.vault.txt

      - run:
          name: pip installations
          command: >
                sudo apt-get install -y python-dev python-pip &&
                pip install --upgrade -r requirements.txt

      - run:
          name: Ansible lints
          command: >
                ansible-lint deploy/main.yml

      - run:
          name: Run Integrates tests
          command: >
                python manage.py test

      - run:
          name: Run prospector
          command: >
                prospector -u django app &&
                prospector -u django fluidintegrates &&
                prospector -u django deploy

      - run:
          name: Run settings check
          command: >
                grep ^DEBUG fluidintegrates/settings.py | grep -q False;

      - run:
          name: Docker login
          command: >
                sudo aws configure set aws_access_key_id $AWS_KEY_ID &&
                sudo aws configure set aws_secret_access_key $AWS_SECRET_KEY &&
                sudo aws ecr get-login --region us-east-1 >> login.sh && sudo sh login.sh

      - run:
          name: Build integrates container
          command: sudo deploy/containers/integrates/build.sh $CIRCLE_BRANCH
          args:
            chdir: deploy/containers/integrates/

      - run:
          name: Build bot container
          command: sudo deploy/containers/bot/build.sh $CIRCLE_BRANCH
          args:
            chdir: deploy/containers/bot/

      - run:
          name: Run asserts
          command: python deploy/asserts-checks.py

      # Deploy master
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then sudo aws configure set aws_access_key_id $AWS_KEY_ID && \
              sudo aws configure set aws_secret_access_key $AWS_SECRET_KEY && \
              sudo aws ecr get-login --region us-east-1 >> login.sh && sudo sh login.sh && \
              sudo docker -D push 205810638802.dkr.ecr.us-east-1.amazonaws.com/integrates:master;
            fi
