apiVersion: v1
kind: Service
metadata:
  name: service-$CI_COMMIT_REF_SLUG
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: integrates-$CI_COMMIT_REF_SLUG
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: review-$CI_COMMIT_REF_SLUG
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: integrates-$CI_COMMIT_REF_SLUG
    spec:
      containers:
      - name: integrates
        image: registry.gitlab.com/fluidsignal/integrates:$CI_COMMIT_REF_SLUG
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: env-secret
        ports:
        - containerPort: 443
      imagePullSecrets:
      - name: gitlab-reg
