apiVersion: v1
kind: Service
metadata:
  name: service-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  namespace: gitlab-managed-apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  namespace: gitlab-managed-apps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    spec:
      containers:
      - name: fluid-$CI_PROJECT_NAME
        image: registry.gitlab.com/fluidsignal/integrates:base
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: $K8_ENV_SECRET
        ports:
        - containerPort: 443
      imagePullSecrets:
      - name: $K8_REG_SECRET
