apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-$CI_PROJECT_NAME
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  namespace: gitlab-managed-apps
spec:
  tls:
  - hosts:
    - $CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME.$ENV_DNS
    secretName: $K8_SSL_SECRET
  rules:
  - host: $CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME.$ENV_DNS
    http:
      paths:
      - backend:
          serviceName: service-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
          servicePort: 80
