apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-$CI_PROJECT_NAME
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "WWW-Authenticate: OAuth realm=\"Access to FLUIDIntegrates\" charset=\"UTF-8\"";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "X-Permitted-Cross-Domain-Policies: master-only";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Pragma: no-cache";
      more_set_headers "Expires: 0";
      more_set_headers "Content-Security-Policy: script-src 'self' 'unsafe-inline' *.mxpnl.com *.cloudflare.com *.intercomcdn.com *.intercom.io *.pingdom.net;";
spec:
  tls:
  - hosts:
    - $CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME.$ENV_DNS
    secretName: $K8_TLS_SECRET
  rules:
  - host: $CI_COMMIT_REF_SLUG.$CI_PROJECT_NAME.$ENV_DNS
    http:
      paths:
      - backend:
          serviceName: service-$CI_COMMIT_REF_SLUG
          servicePort: 80
