apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: $DOCKER_EMAIL
    dns01:
      providers:
      - name: route53
        route53:
          region: $DNS_REGION
          accesskeyID: $FI_RA_AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: $K8_AWS_SECRET
            key: sec-key
          hostedZoneID: $DNS_ZONE_ID
    privateKeySecretRef:
      name: $K8_TLS_KEY
    server: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-template
spec:
  acme:
    config:
    - dns01:
        provider: route53
      domains:
        - '*.$CI_PROJECT_NAME.$ENV_DNS'
  dnsNames:
  - '*.$CI_PROJECT_NAME.$ENV_DNS'
  issuerRef:
    kind: Issuer
    name: cert-issuer
  secretName: $K8_TLS_SECRET
