apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cert-issuer
spec:
  acme:
    email: technology@fluidattacks.com
    dns01:
      providers:
      - name: route53
        route53:
          region: us-east-1
          accesskeyID: $RA_ACCESS_KEY
          secretAccessKeySecretRef:
            name: ra-aws
            key: sec-key
          hostedZoneID: $DNS_ZONE_ID
    privateKeySecretRef:
      name: letsencrypt-key
    server: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert-template
spec:
  acme:
    config:
    - dns01:
        provider: route53
      domains:
        - '*.$CI_PROJECT_NAME.env.fluidattacks.com'
  dnsNames:
  - '*.$CI_PROJECT_NAME.env.fluidattacks.com'
  issuerRef:
    kind: Issuer
    name: cert-issuer
  secretName: ssl-secret
