apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  VAULT_HOST: $VAULT_HOST
  VAULT_TOKEN: $VAULT_TOKEN
# ---
# apiVersion: v1
# data:
#   sec-key: $FI_RA_AWS_SECRET_ACCESS_KEY
# kind: Secret
# metadata:
#   name: $K8_AWS_SECRET
# type: Opaque