---
- hosts: localhost

  become: "yes"

  vars:
    DRIVE_AUTHORIZATION:  "{{ lookup('env','FI_DRIVE_AUTHORIZATION') }}"
    machine: "{{ lookup('env','FI_GITLAB_MACHINE') }}"
    login: "{{ lookup('env','FI_GITLAB_LOGIN') }}"
    password:  "{{ lookup('env','FI_GITLAB_PASSWORD') }}"
    documentroot:  "{{ lookup('env','FI_DOCUMENTROOT') }}"

  tasks:
   - name: Incluir llaves de cifrado
     include_vars: vars/key.yml

   - name: Instalando certificado digital
     copy:
      content: '{{ ssl_cert }}'
      dest: /etc/ssl/certs/fluidla.crt
      owner: root
      group: root
      mode: 0644

   - name: Instalando llave privada ssl
     copy:
      content: '{{ ssl_key }}'
      dest: /etc/ssl/private/fluidla.key
      owner: root
      group: root
      mode: 0600
     notify:
      - reiniciar apache2

  handlers:
   - name: reiniciar apache2
     service:
      name: "apache2"
      state: "restarted"
