---
- hosts: localhost

  become: "yes"

  vars:
    DRIVE_AUTHORIZATION:  "{{ lookup('env','FI_DRIVE_AUTHORIZATION') }}"
    machine: "{{ lookup('env','FI_GITLAB_MACHINE') }}"
    login: "{{ lookup('env','FI_GITLAB_LOGIN') }}"
    password:  "{{ lookup('env','FI_GITLAB_PASSWORD') }}"
    documentroot:  "{{ lookup('env','FI_DOCUMENTROOT') }}"

  tasks:
   - name: Incluir llaves de cifrado
     include_vars: vars/key.yml

   - name: Agregar drive authorization
     template:
      src: "vars/drive_authorization.j2"
      dest: "/usr/src/app/config/drive_authorization.json"
      mode: "0644"
      owner: www-data
      group: www-data

   - name: Instala los paquetes de package.json.
     npm:
      path: "/usr/src/app/app/assets"

   - name: Creando sitio web HTTPS
     template:
      src: "vars/integrates-ssl.j2"
      dest: "/etc/apache2/sites-available/integrates-ssl.conf"
      mode: "0644"

   - name: Creando sitio web HTTP
     template:
      src: "vars/default.j2"
      dest: "/etc/apache2/sites-available/000-default.conf"
      mode: "0644"

   - name: Habilitar sitio integrates HTTPS
     command: "a2ensite integrates-ssl.conf"

   - name: Habilitar sitio integrates HTTP
     command: "a2ensite 000-default.conf"

   - name: Instalando certificado digital
     copy:
      content: '{{ ssl_cert }}'
      dest: /etc/ssl/certs/fluidla.crt
      owner: root
      group: root
      mode: 0644

   - name: Instalando llave privada ssl
     copy:
      content: '{{ ssl_key }}'
      dest: /etc/ssl/private/fluidla.key
      owner: root
      group: root
      mode: 0600
     notify:
      - reiniciar apache2

  handlers:
   - name: reiniciar apache2
     service:
      name: "apache2"
      state: "restarted"
