env:
  browser: true
  node: true

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - unicorn
  - angular

rules:
# Filename Rules
  unicorn/filename-case:
    - error
    - case: camelCase
# Javascript Rules
  for-direction: error
  getter-return: error
  no-await-in-loop: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: error
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens:
    - error
    - all
    - nestedBinaryExpressions: false
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: error
  valid-jsdoc: error
  valid-typeof: error
  accessor-pairs: error
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  complexity: error
  consistent-return: error
  curly: error
  default-case: error
  dot-location: error
  dot-notation: error
  eqeqeq:
    - error
    - smart
  guard-for-in: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers:
    - error
    - enforceConst: true
  no-multi-spaces:
    - error
    - ignoreEOLComments: false
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-redeclare: error
  no-restricted-properties: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: error
  no-with: error
  prefer-promise-reject-errors: error
  radix: error
  require-await: error
  vars-on-top: error
  wrap-iife: error
  yoda: error
  strict: error
  init-declarations: error
  no-catch-shadow: error
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: error
  no-undefined: error
  no-unused-vars:
    - error
    - vars: local
  no-use-before-define: error
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-restricted-modules: error
  no-sync: error
  array-bracket-newline: error
  array-bracket-spacing: error
  array-element-newline: error
  block-spacing: error
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: false
  camelcase: error
  capitalized-comments: error
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this:
    - error
    - "vm"
  eol-last: error
  func-call-spacing: error
  func-names: error
  func-name-matching: error
  func-style:  error
  function-paren-newline: error
  id-blacklist: error
  id-length: error
  id-match: error
  implicit-arrow-linebreak: error
  indent:
    - error
    - 2
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  line-comment-position: error
  linebreak-style: error
  lines-around-comment: error
  lines-between-class-members: error
  max-depth: error
  max-len: error
  max-lines:
   - error
   - max: 500
  max-nested-callbacks: error
  max-statements-per-line: error
  multiline-comment-style: error
  multiline-ternary: error
  new-cap: error
  new-parens: error
  newline-per-chained-call: error
  no-array-constructor: error
  no-bitwise: error
  no-continue: error
  no-inline-comments: error
  no-lonely-if: error
  no-mixed-operators: error
  no-mixed-spaces-and-tabs: error
  no-multi-assign: error
  no-multiple-empty-lines: error
  no-negated-condition: error
  no-nested-ternary: error
  no-new-object: error
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax: error
  no-tabs: error
  no-ternary: error
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: error
  object-property-newline: error
  one-var:
    - error
    - never
  one-var-declaration-per-line: error
  operator-assignment: error
  operator-linebreak: error
  padded-blocks:
    - error
    - never
  padding-line-between-statements: error
  quote-props: error
  quotes: error
  require-jsdoc: error
  semi: error
  semi-spacing: error
  semi-style: error
  sort-keys: error
  sort-vars: error
  space-before-blocks: error
  space-before-function-paren: error
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  wrap-regex: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: error
  no-class-assign: error
  no-confusing-arrow: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: error
  no-restricted-imports: error
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  prefer-const: error
  prefer-destructuring:
    - error
    - VariableDeclarator:
        array: false # Desactivada por elementos Jquery presentes en el código
        object: true
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  require-yield: error
  rest-spread-spacing: error
  sort-imports: error
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error
# Angular Rules
  angular/avoid-scope-typos: error
  angular/module-getter: error
  angular/module-setter: error
  angular/no-private-call: error
  angular/controller-as-route: error
  angular/controller-as-vm: error
  angular/di-unused: error
  angular/directive-restrict: error
  angular/empty-controller: error
  angular/no-inline-template: error
  angular/no-run-logic: error
  angular/no-services:
    - error
    - controller: ['$q'] # Allow the use of $q elements in controllers.
  angular/on-watch: error
  angular/prefer-component: error
  angular/no-cookiestore: error
  angular/no-directive-replace: error
  angular/no-http-callback: error
  angular/component-name: error
  angular/constant-name: error
  angular/directive-name: error
  angular/factory-name: error
  angular/file-name: error
  angular/filter-name: error
  angular/module-name: error
  angular/provider-name: error
  angular/service-name: error
  angular/value-name: error
  angular/di-order: error
  angular/dumb-inject: error
  angular/module-dependency-order: error
  angular/no-service-method: error
  angular/one-dependency-per-line: error
  angular/rest-service: error
  angular/watchers-execution: error
  angular/angularelement: error
  angular/definedundefined: error
  angular/document-service: error
  angular/foreach: error
  angular/interval-service: error
  angular/json-functions: error
  angular/log: error
  angular/no-angular-mock: error
  angular/no-jquery-angularelement: error
  angular/timeout-service: error
  angular/typecheck-array: error
  angular/typecheck-date: error
  angular/typecheck-function: error
  angular/typecheck-number: error
  angular/typecheck-object: error
  angular/typecheck-string: error
  angular/window-service: error
  angular/on-destroy: error
